import {Children,createContext,isValidElement,useContext,useEffect,useState,type ReactNode,type MouseEvent} from 'react';
type Location={pathname:string;state:unknown};
const Context=createContext<{location:Location;navigate:(path:string,options?:{state?:unknown})=>void}|null>(null);
export function BrowserRouter({children}:{children:ReactNode}){const [location,setLocation]=useState<Location>({pathname:window.location.pathname,state:history.state});useEffect(()=>{const pop=()=>setLocation({pathname:window.location.pathname,state:history.state});window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);function navigate(path:string,options?:{state?:unknown}){history.pushState(options?.state||null,'',path);setLocation({pathname:path,state:options?.state||null});window.scrollTo(0,0);}return <Context.Provider value={{location,navigate}}>{children}</Context.Provider>;}
export function useNavigate(){return useContext(Context)!.navigate;}
export function useLocation(){return useContext(Context)!.location;}
export function NavLink({to,children,className,end:_end}:{to:string;children:ReactNode;className?:string|((s:{isActive:boolean})=>string);end?:boolean}){const {location,navigate}=useContext(Context)!;const active=location.pathname===to;return <a href={to} aria-current={active?'page':undefined} className={typeof className==='function'?className({isActive:active}):className} onClick={(e:MouseEvent)=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||e.button!==0)return;e.preventDefault();navigate(to);}}>{children}</a>;}
export function Route(_props:{path:string;element:ReactNode}){return null;}
export function Routes({children}:{children:ReactNode}){const {pathname}=useLocation();const routes=Children.toArray(children).filter(isValidElement<{path:string;element:ReactNode}>);const match=routes.find(r=>r.props.path===pathname)||routes.find(r=>r.props.path==='*');return match?<div key={pathname}>{match.props.element}</div>:null;}
