import {writeFile} from 'node:fs/promises';
import {config} from '../../server/config.ts';
if (!config.openaiKey) throw new Error('TTS unavailable: server key missing');
const input = "Uma apresentação pode estar bem montada e ainda travar na hora das perguntas. A pessoa conhece a ideia, mas precisa explicar o valor, defender uma escolha e adaptar a resposta a quem está ouvindo.\n\nO Rebobina reúne essa preparação em um produto: você organiza o contexto, pratica a conversa e transforma o feedback em uma nova versão do seu material.\n\nA jornada começa na sua conta. Você escolhe o avatar, ajusta a aparência e leva esse personagem para a sala de ensaio.\n\nEm Materiais, ficam o briefing, as referências e os textos que sustentam a apresentação. É possível colar conteúdo, importar um arquivo de texto, buscar uma informação e retomar o que já foi preparado.\n\nNa audiência, você informa quem vai participar, o papel dessa pessoa e as fontes relevantes. O sistema organiza os temas de avaliação e mostra de onde saiu cada ponto. Assim, o treino acompanha o contexto daquela reunião.\n\nA Mesa transforma esses materiais em trabalho. Você pode preparar um pitch, revisar uma resposta ou encontrar lacunas. O texto fica aberto ao lado da conversa e cada revisão gera uma versão que pode ser retomada depois.\n\nCom o pitch preparado, é hora de entrar na sala. O cenário tridimensional reúne o seu avatar e a audiência escolhida. Você aproxima a câmera, acompanha a pergunta ativa e abre a referência quando precisa entender melhor o contexto.\n\nDepois de responder, recebe uma devolutiva sobre aquela tentativa: o que funcionou, onde o argumento ficou fraco e uma sugestão concreta para melhorar.\n\nO botão Rebobinar permite voltar à pergunta e experimentar outra abordagem. Em seguida, você leva o aprendizado para a Mesa, ajusta o texto e mantém as versões anteriores disponíveis.\n\nHá também um ambiente de atendimento. Nele, você conversa com personagens, consulta informações do negócio, toma decisões e observa o resultado. A mesma lógica de preparação vira um exercício de situações do dia a dia.\n\nPara fundadores, equipes comerciais e estudantes, o valor está em repetir esse ciclo com o próprio material. A preparação deixa de ficar espalhada entre documentos, anotações e conversas soltas.\n\nEsse é o Rebobina: preparar o conteúdo, praticar a conversa e sair do ensaio com uma próxima versão para usar.";
const response = await fetch('https://api.openai.com/v1/audio/speech',{
 method:'POST',headers:{Authorization:`Bearer ${config.openaiKey}`,'Content-Type':'application/json'},
 signal:AbortSignal.timeout(180000),
 body:JSON.stringify({model:'gpt-4o-mini-tts',voice:'coral',response_format:'mp3',speed:1.03,
 instructions:'Português brasileiro. Apresentação de produto por uma fundadora confiante, clara e objetiva. Ritmo conversado de pitch, cerca de 150 palavras por minuto. Pausas curtas entre parágrafos. Evite voz de anúncio, solenidade ou dramaticidade. Diga Rebobina com naturalidade. Não leia instruções.',input})
});
if(!response.ok)throw new Error(`TTS HTTP ${response.status}`);
const bytes=new Uint8Array(await response.arrayBuffer());
await writeFile('artifacts/demo/rebobina-pitch-v6-voz-original.mp3',bytes);
console.log(JSON.stringify({ok:true,voice:'coral',bytes:bytes.length}));

