import type express from 'express';
import {z} from 'zod';
import type {Workspace} from '../shared/types.js';
import type {AudienceProfile, EvidenceRef, MapAudienceInput,GenerateRehearsalInput,EvaluateAnswerInput,RehearsalSession,RehearsalTurn,SourceDocument} from '../shared/rehearsal-types.js';
import * as rehearsalService from './rehearsal/service.js';
type Api=(fn:(req:express.Request,w:Workspace)=>Promise<unknown>|unknown,save?:boolean)=>express.RequestHandler;
interface Service{mapAudience:(input:MapAudienceInput)=>Promise<AudienceProfile>;generateRehearsal:(input:GenerateRehearsalInput)=>Promise<RehearsalSession>;evaluateAnswer:(input:EvaluateAnswerInput)=>Promise<RehearsalTurn>}
async function service():Promise<Service>{return rehearsalService;}
function state(w:Workspace){return w.rehearsal??=( {audiences:[],sessions:[],activeSessionId:null} );}
function sources(w:Workspace,ids:string[]):SourceDocument[]{const unique=[...new Set(ids)];return unique.map(id=>{const m=w.materials.find(m=>m.id===id);if(!m)throw new Error('Uma das fontes não pertence a este espaço.');return {id:m.id,title:m.title,content:m.content};});}
function verifyRefs(refs:EvidenceRef[],docs:SourceDocument[]){for(const ref of refs){const doc=docs.find(d=>d.id===ref.sourceId);if(!doc||!ref.quote.trim()||!doc.content.includes(ref.quote))throw new Error('Uma referência não corresponde aos materiais. Gere novamente; não vamos salvar uma citação sem lastro.');}}
function audienceSourceIds(a:AudienceProfile){return a.sourceIds||a.lenses.flatMap(l=>l.evidence.map(e=>e.sourceId));}
function sessionSources(w:Workspace,s:RehearsalSession){const ids=s.audiences.flatMap(audienceSourceIds);if(s.artifactId){const artifact=w.materials.find(m=>m.id===s.artifactId);if(artifact)ids.push(...artifact.sources);}return sources(w,ids);}
export function registerRehearsalRoutes(app:express.Express,api:Api){
 app.get('/api/rehearsal/state',api((_req,w)=>state(w),false));
 app.post('/api/rehearsal/audience',api(async(req,w)=>{const input=z.object({name:z.string().trim().min(1).max(80),role:z.string().trim().min(1).max(150),sourceIds:z.array(z.string()).min(1).max(8)}).parse(req.body);const current=state(w);if(current.audiences.length>=15)throw new Error('Limite de 15 perfis deste protótipo atingido.');const docs=sources(w,input.sourceIds);if(docs.reduce((n,d)=>n+d.content.length,0)>24000)throw new Error('Selecione fontes com até 24 mil caracteres no total.');const profile=await(await service()).mapAudience({...input,sources:docs});for(const lens of profile.lenses)verifyRefs(lens.evidence,docs);profile.id=crypto.randomUUID();profile.name=input.name;profile.role=input.role;profile.sourceIds=docs.map(d=>d.id);profile.createdAt=new Date().toISOString();if(docs.some(d=>/exemplo sint[eé]tico|perfil fict[ií]cio|pessoa fict[ií]cia/i.test(d.title+' '+d.content)))profile.synthetic=true;current.audiences.push(profile);return {profile,workspace:current};}));
 app.post('/api/rehearsal/generate',api(async(req,w)=>{const input=z.object({pitch:z.string().trim().min(30).max(12000),audienceIds:z.array(z.string()).min(1).max(3),artifactId:z.string().optional()}).parse(req.body);const current=state(w);if(current.sessions.length>=50)throw new Error('Limite de ensaios deste protótipo atingido.');const ids=[...new Set(input.audienceIds)];const audiences=ids.map(id=>{const a=current.audiences.find(a=>a.id===id);if(!a)throw new Error('Audiência não encontrada neste espaço.');return structuredClone(a);});if(input.artifactId&&!w.materials.some(m=>m.id===input.artifactId&&m.kind==='artifact'))throw new Error('Material de trabalho não encontrado neste espaço.');const docs=sources(w,audiences.flatMap(audienceSourceIds));const result=await(await service()).generateRehearsal({pitch:input.pitch,audiences,sources:docs,artifactId:input.artifactId});if(!result.questions?.length||result.questions.length>3)throw new Error('O ensaio precisa de uma a três perguntas.');for(const q of result.questions){if(!audiences.some(a=>a.id===q.audienceId))throw new Error('Pergunta vinculada a audiência desconhecida.');verifyRefs(q.evidence,docs);if(!q.evidence.length)q.speculative=true;}
 result.id=crypto.randomUUID();result.pitch=input.pitch;result.audiences=audiences;result.turns=[];result.createdAt=new Date().toISOString();result.artifactId=input.artifactId;current.sessions.push(result);current.activeSessionId=result.id;return {session:result,workspace:current};}));
 app.post('/api/rehearsal/answer',api(async(req,w)=>{const input=z.object({sessionId:z.string(),questionId:z.string(),answer:z.string().trim().min(3).max(6000)}).parse(req.body);const current=state(w),s=current.sessions.find(s=>s.id===input.sessionId);if(!s)throw new Error('Ensaio não encontrado neste espaço.');const next=s.questions[s.turns.length];if(!next||next.id!==input.questionId)throw new Error('Responda a pergunta atual. Para mudar uma resposta anterior, rebobine.');const docs=sessionSources(w,s);const turn=await(await service()).evaluateAnswer({session:structuredClone(s),questionId:input.questionId,answer:input.answer,sources:docs});verifyRefs(turn.feedback.evidence,docs);turn.id=crypto.randomUUID();turn.questionId=input.questionId;turn.answer=input.answer;turn.createdAt=new Date().toISOString();s.turns.push(turn);current.activeSessionId=s.id;return {turn,workspace:current};}));
 app.post('/api/rehearsal/rewind',api((req,w)=>{const input=z.object({sessionId:z.string(),keepTurns:z.number().int().min(0).max(3)}).parse(req.body);const current=state(w),parent=current.sessions.find(s=>s.id===input.sessionId);if(!parent||input.keepTurns>parent.turns.length)throw new Error('Ponto de retorno inválido.');if(current.sessions.length>=50)throw new Error('Limite de ensaios deste protótipo atingido.');const result:RehearsalSession={...structuredClone(parent),id:crypto.randomUUID(),parentSessionId:parent.id,turns:structuredClone(parent.turns.slice(0,input.keepTurns)),createdAt:new Date().toISOString()};current.sessions.push(result);current.activeSessionId=result.id;return {session:result,workspace:current};}));
}
