import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {ArrowRight,BookOpen,CheckCircle2,ChevronDown,FileText,List,MessageCircle,Play,RotateCcw,Send,Sparkles,X} from 'lucide-react';
import WorldScene from '../components/WorldScene';
import CreateScenario from '../components/CreateScenario';
import {useWorkspace} from '../lib/workspace';
import {api} from '../lib/api';
import {actions,currentState} from '../../shared/engine';
export default function WorldPage(){const {workspace,mutate,busy,notify}=useWorkspace();const navigate=useNavigate();const [create,setCreate]=useState(false),[list,setList]=useState(false),[characterId,setCharacter]=useState<string|null>(null),[message,setMessage]=useState(''),[reply,setReply]=useState(''),[talking,setTalking]=useState(false);const attempt=workspace.attempts.find(a=>a.id===workspace.activeAttemptId)||workspace.attempts[0];const scenario=attempt.scenario,state=currentState(attempt);const character=scenario.characters.find(c=>c.id===characterId);const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const artifact=workspace.materials.find(m=>m.id===scenario.artifactId);
 async function talk(){if(!message.trim())return;setTalking(true);setReply('');try{const r=await api<{reply:string}>('/roleplay',{characterId,message});setReply(r.reply);setMessage('');}catch(e){notify((e as Error).message);}finally{setTalking(false);}}
 function choose(id:Parameters<typeof mutate>[1]){void mutate('/action',id).catch(()=>{});}
 return <><header className="page-heading"><div><span className="eyebrow">SEU ESPAÇO PARA EXPERIMENTAR</span><h1>Meu mundo<span className="heading-dot">.</span></h1><p>Um lugar seguro para tentar. E tentar diferente.</p></div><button className="button primary" onClick={()=>setCreate(true)}><Sparkles size={17}/> Criar situação</button></header><div className="world-layout"><section className="world-canvas"><div className="world-toolbar"><div><span className="live-dot"/> {scenario.businessName} <ChevronDown size={14}/></div><button className="subtle-button" onClick={()=>setList(!list)} aria-pressed={list}><List size={15}/>{list?'Ver mundo':'Modo lista'}</button></div><div className="scene-label"><span className="tag">{scenario.generation==='ai'?'Personalizado com IA':'Mundo de exemplo'}</span><span className="scene-label-small">ATENDIMENTO · SIMULAÇÃO</span></div>{list?<div className="world-list"><h2>Quem está no seu mundo</h2>{scenario.characters.map(c=><button key={c.id} onClick={()=>{setCharacter(c.id);setReply('');}}><span className="avatar" style={{background:c.color}}>{c.name[0]}</span><span><b>{c.name}</b><small>{c.greeting}</small></span><ArrowRight size={17}/></button>)}</div>:<WorldScene scenario={scenario} state={state} reducedMotion={reducedMotion} onCharacter={id=>{setCharacter(id);setReply('');}} onStation={station=>navigate(station==='work'?'/mesa':'/materiais')}/>}
 <div className="world-caption"><span><MessageCircle size={15}/> Converse com os personagens ou use o painel ao lado.</span><span>Sem consequências no mundo real</span></div></section><aside className="mission-panel"><div className="section-kicker"><span className="tiny-circle"><Play size={12} fill="currentColor"/></span> SEU PRÓXIMO ENSAIO</div><h2>{scenario.title}</h2><p className="mission-objective">{scenario.objective}</p><div className="request-note"><span className="mini-label">O PEDIDO</span><p>{scenario.requested} {scenario.product} em {scenario.requestedDays} dia(s).</p></div>{artifact&&<button className="linked-artifact" onClick={()=>navigate('/mesa',{state:{artifactId:artifact.id}})}><FileText size={16}/> Seu material · v{artifact.version}</button>}<div className="suggestion"><div><Sparkles size={15}/><b>Sugestão da assistente</b></div><p>“{scenario.suggestion}”</p><small>Sugestão construída para o exercício. Avalie com as fontes.</small></div>
 {state.consulted&&<div className="source-evidence"><b><BookOpen size={15}/> O que consta nas fontes</b><p>Estoque: {scenario.stock??'não informado'} · Prazo: {scenario.deliveryDays===null?'não informado':`${scenario.deliveryDays} dia(s)`}</p>{scenario.facts.map(f=><blockquote key={f.label}>“{f.quote}”</blockquote>)}</div>}
 {!state.resolved?<div className="action-list">{actions.filter(a=>a.id!=='verify'||!state.consulted).map(a=><button key={a.id} disabled={busy} onClick={()=>choose({action:a.id})} className={a.id==='verify'?'action-button featured':'action-button'}><span><b>{a.label}</b><small>{a.description}</small></span><ArrowRight size={16}/></button>)}</div>:<div className={`outcome ${state.issues.length?'warning':''}`} role="status"><CheckCircle2 size={22}/><h3>{state.outcome}</h3><p>{attempt.events.at(-1)?.explanation}</p>{state.issues.map(issue=><p className="issue" key={issue}>{issue}</p>)}<button className="button primary wide" disabled={busy} onClick={()=>void mutate('/rewind',{attemptId:attempt.id,count:0}).catch(()=>{})}><RotateCcw size={16}/> Rebobinar minha decisão</button><button className="text-button" onClick={()=>navigate('/tentativas')}>Entender esta tentativa <ArrowRight size={15}/></button></div>}</aside></div>
 <div className="bottom-path"><div><span className="path-number">01</span><div><b>Prepare com contexto</b><small>Uma resposta, um plano, uma ideia.</small></div></div><ArrowRight size={18}/><div><span className="path-number">02</span><div><b>Experimente no seu mundo</b><small>Escolha. Observe o que muda.</small></div></div><ArrowRight size={18}/><div><span className="path-number">03</span><div><b>Volte com outra perspectiva</b><small>Rebobine e revise seu material.</small></div></div></div>
 {character&&<section className="character-panel" aria-label={`Conversa com ${character.name}`}><button className="icon-button close-character" onClick={()=>setCharacter(null)} aria-label="Fechar conversa"><X size={18}/></button><span className="eyebrow">PERSONAGEM DO EXERCÍCIO</span><h3>{character.name}</h3><p>{character.greeting}</p>{reply&&<p className="character-reply" role="status">{reply}</p>}<form onSubmit={e=>{e.preventDefault();void talk();}}><input aria-label="Mensagem ao personagem" value={message} maxLength={1500} onChange={e=>setMessage(e.target.value)} placeholder="Pergunte algo…"/><button className="icon-button" disabled={talking||!message.trim()} aria-label="Enviar mensagem"><Send size={17}/></button></form><small>{talking?'O personagem está respondendo…':'A conversa não altera o pedido. Use os botões de decisão.'}</small></section>}{create&&<CreateScenario open onClose={()=>setCreate(false)}/>}</>;
}
