import {useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {ArrowRight,Check,LoaderCircle,Sparkles,X} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {api} from '../lib/api';
import {useWorkspace} from '../lib/workspace';
import type {Scenario} from '../../shared/types';
interface Props{open:boolean;onClose:()=>void;initialContext?:string;sourceMaterialId?:string;artifactId?:string}
const templates=[{label:'Café',text:'Meu negócio é o Café Aurora. Produto: caixas de café. Estoque: 4. Prazo de entrega: 2 dias. Cliente pede 8 caixas para amanhã (1 dia).'},{label:'Floricultura',text:'Tenho a Flor de Bairro. Produto: buquês. Estoque: 12. Prazo de entrega: 1 dia. Uma cliente quer 6 buquês para daqui a 2 dias.'},{label:'Informação ausente',text:'Tenho uma papelaria chamada Ponto de Encontro. Produto: kits de cadernos. Estoque: 10. Cliente pede 5 kits para amanhã. Não tenho prazo de entrega confirmado.'}];
export default function CreateScenario({open,onClose,initialContext='',sourceMaterialId,artifactId}:Props){const [context,setContext]=useState(initialContext),[loading,setLoading]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<Scenario|null>(null),[branches,setBranches]=useState(0);const {mutate,notify}=useWorkspace();const navigate=useNavigate();
 async function generate(){setLoading(true);setError('');try{const result=await api<{scenario:Scenario;exploration:{terminal:number}}>('/generate',{context,sourceMaterialId,artifactId});setPreview(result.scenario);setBranches(result.exploration.terminal);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 async function activate(){if(!preview)return;setLoading(true);try{await mutate('/activate',{id:preview.id});onClose();navigate('/');notify('Seu cenário está pronto. Comece pelo atendimento.');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 return <Dialog.Root open={open} onOpenChange={v=>{if(!v&&!loading)onClose();}}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-panel"><Dialog.Close className="icon-button dialog-close" aria-label="Fechar" disabled={loading}><X size={20}/></Dialog.Close><span className="eyebrow"><Sparkles size={15}/> UM MUNDO A PARTIR DO SEU CONTEXTO</span><Dialog.Title>{preview?'Confira antes de entrar':'O que vamos experimentar?'}</Dialog.Title><Dialog.Description>{preview?'Estes fatos serão as regras do exercício. Confira se correspondem ao que você trouxe.':'Traga uma situação de atendimento. A IA compõe o ambiente e os personagens; você confere os fatos.'}</Dialog.Description>
 {!preview?<><label className="field-label" htmlFor="context">Seu contexto</label><textarea id="context" value={context} onChange={e=>setContext(e.target.value)} maxLength={12000} rows={7} placeholder="Qual é o negócio? O que o cliente pede? Quais condições você conhece?"/><div className="template-row"><span>Experimentar com:</span>{templates.map(t=><button key={t.label} className="chip" onClick={()=>setContext(t.text)}>{t.label}</button>)}</div><p className="fine-print">Use dados de exemplo, sem nomes de clientes ou informações sensíveis. O contexto será enviado ao provedor de IA.</p><button className="button primary wide" disabled={loading||context.trim().length<15} onClick={generate}>{loading?<><LoaderCircle className="spin" size={18}/> Compondo e verificando seu cenário…</>:<><Sparkles size={18}/> Gerar meu mundo <ArrowRight size={18}/></>}</button></>:<><div className="preview-heading"><span className="tag green">Gerado com IA</span><h3>{preview.businessName}</h3><p>{preview.objective}</p></div><dl className="facts-grid"><div><dt>Produto</dt><dd>{preview.product}</dd></div><div><dt>Estoque</dt><dd>{preview.stock??'Não informado'}</dd></div><div><dt>Prazo informado</dt><dd>{preview.deliveryDays===null?'Não informado':`${preview.deliveryDays} dia(s)`}</dd></div><div><dt>Pedido do exercício</dt><dd>{preview.requested} unidades / {preview.requestedDays} dia(s)</dd></div></dl>{preview.facts.map(f=><blockquote key={f.label}><b>{f.label}</b> — “{f.quote}”</blockquote>)}<details><summary>O que é simulação e o que foi verificado</summary><ul>{preview.assumptions.map((a,i)=><li key={i}>{a}</li>)}</ul><p>{branches} caminhos terminais verificados no motor: consulta opcional e uma decisão. Isso não prevê resultados reais.</p></details><div className="button-row"><button className="button secondary" disabled={loading} onClick={()=>setPreview(null)}>Revisar contexto</button><button className="button primary" disabled={loading} onClick={activate}><Check size={18}/> Conferi os fatos. Entrar</button></div></>}{error&&<p className="error" role="alert">{error}</p>}</Dialog.Content></Dialog.Portal></Dialog.Root>;
}
