import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const origin=(process.env.REBOBINA_BASE_URL||'http://localhost:4173').replace(/\/$/,'');
const base=origin+'/api';
const reportFile=process.env.REBOBINA_BASE_URL?'artifacts/qa/root-integration-public.json':'artifacts/qa/root-integration.json';
let cookie='';const checks:string[]=[];
async function request(path:string,body?:unknown,isolated=false){const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json',...(!isolated&&cookie?{cookie}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(65000)});if(!cookie&&!isolated)cookie=r.headers.get('set-cookie')?.split(';')[0]||'';if(!r.headers.get('content-type')?.includes('application/json'))throw new Error(`${path}: HTTP ${r.status}, resposta não JSON; verificar runtime do deploy.`);const data=await r.json();return {status:r.status,data};}
async function ok(path:string,body?:unknown){const r=await request(path,body);assert.equal(r.status,200,`${path}: ${r.data.error||r.status}`);return r.data;}
try{
 const health=await ok('/health');assert.equal(health.storage,'postgres');checks.push('PostgreSQL connected');
 const sourceText='EXEMPLO SINTÉTICO — pessoa fictícia para demonstração. Ana é uma avaliadora de projetos sociais. Na rubrica deste exemplo, ela pede evidências de impacto observado, distingue hipótese de resultado e quer saber como uma pessoa com pouca experiência usa a solução. Este texto é um material de treinamento fictício, não uma biografia real.';
 const {material}=await ok('/materials',{title:'Exemplo sintético — critérios profissionais de Ana',content:sourceText});checks.push('Source persisted');
 const {profile}=await ok('/rehearsals/audience',{name:'Ana — exemplo fictício',role:'Avaliadora de impacto social',sourceIds:[material.id]});assert.ok(profile.lenses.length);assert.ok(profile.synthetic||profile.isFictional);for(const l of profile.lenses)for(const ref of l.evidence){assert.equal(ref.sourceId,material.id);assert.ok(sourceText.includes(ref.quote));}checks.push('Live AI audience mapping with anchored quotes');
 const pitch='Rebobina ajuda pessoas a ensaiar apresentações com IA. A pessoa traz seu pitch e documentos profissionais sobre a audiência, recebe perguntas plausíveis fundamentadas, responde, revisa com feedback e rebobina. Temos um protótipo funcional, mas ainda não comprovamos ganho de aprendizagem com usuários. A experiência tem uma sala 2.5D e alternativa em lista.';
 const {session}=await ok('/rehearsals/generate',{pitch,audienceIds:[profile.id]});assert.ok(session.questions.length>0&&session.questions.length<=3);for(const q of session.questions)for(const ref of q.evidence)assert.ok(sourceText.includes(ref.quote));checks.push('Live AI questions generated from pitch and audience');
 const question=session.questions[0];const {turn}=await ok('/rehearsals/answer',{sessionId:session.id,questionId:question.id,answer:'Hoje comprovamos somente o funcionamento do protótipo. Ainda não fizemos teste com pessoas; o próximo passo é comparar respostas antes e depois do ensaio com critérios de clareza e evidência. Não vamos prometer aprendizagem validada nesta apresentação.'});assert.ok(turn.feedback.suggestion);checks.push('Live answer feedback');
 const duplicate=await request('/rehearsals/answer',{sessionId:session.id,questionId:question.id,answer:'Tentativa duplicada'});assert.equal(duplicate.status,400);checks.push('Duplicate answer rejected');
 const {session:branch}=await ok('/rehearsals/rewind',{sessionId:session.id,keepTurns:0});assert.notEqual(branch.id,session.id);assert.equal(branch.turns.length,0);assert.equal(branch.parentSessionId,session.id);
 const state=await ok('/rehearsals/state');assert.equal(state.sessions.find((s:{id:string})=>s.id===session.id).turns.length,1);checks.push('Rewind preserves original; reload persists branch');
 const separate=await request('/rehearsals/state',undefined,true);assert.equal(separate.data.sessions.length,0);checks.push('Independent browser session isolated');
 const forbidden=await request('/rehearsals/audience',{name:'Outro perfil',role:'Teste',sourceIds:['not-owned']});assert.equal(forbidden.status,400);checks.push('Foreign source rejected');
 const {material:artifact}=await ok('/work',{prompt:'Prepare um pitch curto do Rebobina. Produto: ensaio de apresentações com perguntas plausíveis a partir de evidências profissionais. Não afirmar previsão de pessoas nem validação de aprendizagem. Use as preocupações do material selecionado para estruturar o pitch.',mode:'work',sourceIds:[material.id]});assert.equal(artifact.version,1);
 const {material:revision}=await ok('/work',{prompt:'Revise este pitch deixando explícito que impacto educacional ainda não foi testado. Preserve o que estiver adequado.',mode:'work',sourceIds:[material.id,artifact.id],parentId:artifact.id});assert.equal(revision.version,2);assert.equal(revision.parentId,artifact.id);const w=await ok('/state');assert.ok(w.materials.find((m:{id:string})=>m.id===artifact.id));checks.push('Work generation and immutable revision persisted');
 await mkdir('artifacts/qa',{recursive:true});const report={status:'PASS_LIVE_INTEGRATION',origin,at:new Date().toISOString(),checks,questions:session.questions.map((q:{text:string})=>q.text),limitations:['Browser QA separate','Synthetic source, real AI requests','No human learning validation']};await writeFile(reportFile,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}catch(error){const report={status:'FAIL',origin,at:new Date().toISOString(),checks,error:(error as Error).message};await mkdir('artifacts/qa',{recursive:true});await writeFile(reportFile,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));process.exitCode=1;}
